name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  # Rubyのセキュリティスキャン
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false  # キャッシュを無効にする

      - name: Install Bundler and dependencies  # Gemをインストール
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  # JavaScriptのセキュリティスキャン
  scan_js:
    ru
